// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma ORM v7 moved connection URLs out of `schema.prisma`.
    // For Supabase: set DIRECT_URL to the non-pooler (5432) connection string for migrations,
    // and DATABASE_URL to the pooler (6543) string for runtime.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
