-- CreateEnum
CREATE TYPE "BedSize" AS ENUM ('INDIVIDUAL', 'DOBLE');

-- CreateEnum
CREATE TYPE "WindowType" AS ENUM ('CALLE', 'CORAZON_DE_MANZANA', 'POZO_DE_AIRE', 'SIN_VENTANA');

-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "apartmentBaths" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "apartmentRooms" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "apartmentSizeSqm" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN     "bedSize" "BedSize" NOT NULL DEFAULT 'INDIVIDUAL',
ADD COLUMN     "furnished" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "roomSizeSqm" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "wifi" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "windowType" "WindowType" NOT NULL DEFAULT 'CALLE';
